<a href="https://colab.research.google.com/github/ishwaridhage10-cpu/NumPy2/blob/main/Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr = np.random.randint(10, 101, (5, 6))

print("Array:")
print(arr)

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Array:
[[83 56 78 70 46 67]
 [18 50 91 45 19 21]
 [53 90 77 80 50 65]
 [60 71 75 72 76 27]
 [72 40 31 13 69 12]]
Shape: (5, 6)
Size: 30
Data Type: int64
