<a href="https://colab.research.google.com/github/ishwaridhage10-cpu/NumPy2/blob/main/Q10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np

# Generate random marks for 10 students and 5 subjects
marks = np.random.randint(30, 101, (10, 5))

# Print the marks array
print("Student Marks:")
print(marks)

# Calculate total and average marks of each student
total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)

print("\nTotal Marks:")
print(total)

print("\nAverage Marks:")
print(average)

# Find student with highest and lowest total marks
highest = np.argmax(total)
lowest = np.argmin(total)

print("\nStudent with Highest Total:", highest + 1)
print("Highest Total Marks:", total[highest])

print("\nStudent with Lowest Total:", lowest + 1)
print("Lowest Total Marks:", total[lowest])

# Calculate overall class mean and standard deviation
print("\nClass Mean:", np.mean(marks))
print("Class Standard Deviation:", np.std(marks))

# Reshape the array (10x5 to 5x10)
reshaped = marks.reshape(5, 10)

print("\nReshaped Array (5x10):")
print(reshaped)

# Extract marks of top 3 students
top3 = np.argsort(total)[-3:]

print("\nTop 3 Students (Marks):")
print(marks[top3])

Student Marks:
[[ 80  37  96  97  44]
 [ 43  78  92  63  56]
 [ 61  57  63  54  89]
 [ 66  89  61  71  56]
 [ 48 100  45  41  58]
 [ 58  53  89  71  83]
 [ 98  63  44  35  47]
 [ 71  77  92  87  75]
 [ 97  70  40  97  99]
 [ 63  59  61  92 100]]

Total Marks:
[354 332 324 343 292 354 287 402 403 375]

Average Marks:
[70.8 66.4 64.8 68.6 58.4 70.8 57.4 80.4 80.6 75. ]

Student with Highest Total: 9
Highest Total Marks: 403

Student with Lowest Total: 7
Lowest Total Marks: 287

Class Mean: 69.32
Class Standard Deviation: 19.617787846747653

Reshaped Array (5x10):
[[ 80  37  96  97  44  43  78  92  63  56]
 [ 61  57  63  54  89  66  89  61  71  56]
 [ 48 100  45  41  58  58  53  89  71  83]
 [ 98  63  44  35  47  71  77  92  87  75]
 [ 97  70  40  97  99  63  59  61  92 100]]

Top 3 Students (Marks):
[[ 63  59  61  92 100]
 [ 71  77  92  87  75]
 [ 97  70  40  97  99]]
