<a href="https://colab.research.google.com/github/ishwaridhage10-cpu/NumPy2/blob/main/Q3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

arr = np.random.randint(20, 81, (4, 5))

print("Matrix:")
print(arr)

print("Minimum Value:", np.min(arr))
print("Maximum Value:", np.max(arr))

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

print("Row-wise Sum:")
print(np.sum(arr, axis=1))

print("Column-wise Sum:")
print(np.sum(arr, axis=0))

Matrix:
[[75 40 59 72 42]
 [41 53 44 36 74]
 [77 33 49 32 39]
 [69 37 39 68 57]]
Minimum Value: 32
Maximum Value: 77
Sum: 1036
Mean: 51.8
Standard Deviation: 15.289211882893115
Row-wise Sum:
[288 248 230 270]
Column-wise Sum:
[262 163 191 208 212]
