<a href="https://colab.research.google.com/github/ishwaridhage10-cpu/NumPy2/blob/main/Q4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

arr = np.arange(1, 25)

print("Original Array:")
print(arr)
print("Shape:", arr.shape)

arr1 = arr.reshape(4, 6)
print("\nShape (4, 6):")
print(arr1)
print("Shape:", arr1.shape)

arr2 = arr.reshape(3, 8)
print("\nShape (3, 8):")
print(arr2)
print("Shape:", arr2.shape)

arr3 = arr.reshape(2, 3, 4)
print("\nShape (2, 3, 4):")
print(arr3)
print("Shape:", arr3.shape)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)

Shape (4, 6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

Shape (3, 8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)

Shape (2, 3, 4):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)
