<a href="https://colab.research.google.com/github/ishwaridhage10-cpu/NumPy2/blob/main/Q6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

arr = np.random.randint(1, 101, (5, 5))

print("Original Matrix:")
print(arr)

print("\nDiagonal Elements:")
print(np.diag(arr))

print("\nElements Greater Than 50:")
print(arr[arr > 50])

arr[arr < 30] = 0

print("\nModified Matrix:")
print(arr)

Original Matrix:
[[64 14 50 98 35]
 [74  2 69 70 10]
 [95  4 34  6 87]
 [84 26 67 10 61]
 [66 36 22 10 87]]

Diagonal Elements:
[64  2 34 10 87]

Elements Greater Than 50:
[64 98 74 69 70 95 87 84 67 61 66 87]

Modified Matrix:
[[64  0 50 98 35]
 [74  0 69 70  0]
 [95  0 34  0 87]
 [84  0 67  0 61]
 [66 36  0  0 87]]
