<a href="https://colab.research.google.com/github/ishwaridhage10-cpu/NumPy2/blob/main/Q7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Array a:")
print(a)

print("Array b:")
print(b)

print("\nAddition:")
print(a + b)

print("\nSubtraction:")
print(a - b)

print("\nMultiplication:")
print(a * b)

print("\nDivision:")
print(a / b)

print("\nElement-wise Power:")
print(a ** b)

print("\nModulo:")
print(a % b)

Array a:
[10 20 30 40]
Array b:
[1 2 3 4]

Addition:
[11 22 33 44]

Subtraction:
[ 9 18 27 36]

Multiplication:
[ 10  40  90 160]

Division:
[10. 10. 10. 10.]

Element-wise Power:
[     10     400   27000 2560000]

Modulo:
[0 0 0 0]
