<a href="https://colab.research.google.com/github/ishwaridhage10-cpu/NumPy2/blob/main/Q8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Element-wise Multiplication:")
print(A * B)      # Multiplies corresponding elements

print("\nMatrix Multiplication:")
print(A @ B)      # Multiplies rows of A with columns of B

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
