<a href="https://colab.research.google.com/github/ishwaridhage10-cpu/NumPy2/blob/main/Q9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

arr = np.random.randn(6, 6)

print("Matrix:")
print(arr)

print("\nShape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

print("\nIndex of Maximum Value:", np.argmax(arr))
print("Index of Minimum Value:", np.argmin(arr))

print("\nTop-Left 3x3 Submatrix:")
print(arr[:3, :3])

arr = np.abs(arr)

print("\nModified Matrix:")
print(arr)

print("\nMean:", np.mean(arr))

Matrix:
[[-0.81541721 -0.54528853  0.71530829  0.20108324  0.87914924 -1.5475    ]
 [-0.28567761  0.61035214 -1.85699716  0.07332193 -2.01931491 -0.88078982]
 [-0.54403552 -0.61179413 -0.62871033  0.88801751 -0.57599315  0.83630035]
 [ 0.21177549  0.41730912  1.41915639  2.07924461  1.5166707   1.09194725]
 [ 0.42916718 -0.00548705  1.6324077   0.58656556 -1.73474217 -0.97082906]
 [-0.45944365 -0.16228072  0.15817399  1.48436068  1.12399097 -2.5007721 ]]

Shape: (6, 6)
Size: 36
Data Type: float64

Index of Maximum Value: 21
Index of Minimum Value: 35

Top-Left 3x3 Submatrix:
[[-0.81541721 -0.54528853  0.71530829]
 [-0.28567761  0.61035214 -1.85699716]
 [-0.54403552 -0.61179413 -0.62871033]]

Modified Matrix:
[[0.81541721 0.54528853 0.71530829 0.20108324 0.87914924 1.5475    ]
 [0.28567761 0.61035214 1.85699716 0.07332193 2.01931491 0.88078982]
 [0.54403552 0.61179413 0.62871033 0.88801751 0.57599315 0.83630035]
 [0.21177549 0.41730912 1.41915639 2.07924461 1.5166707  1.09194725]
 [0.42